branches:
  only:
    - develop
    - master

language: php

php: 
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_ARGS=""
    - COMPOSER_ARGS="--prefer-lowest"

install:
  - composer update ${COMPOSER_ARGS} --dev --no-interaction

script:
  - vendor/bin/phpunit --verbose

sudo: false
